version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: dev-rabbitmq
    container_name: some-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - C:\Users\KDUWADI\Desktop\NREL_Projects\TUNISIA\data\evolve_docker_data\rabbitmq_data:/var/lib/rabbitmq
  postgres:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evolve
    ports:
      - 5433:5432
    volumes:
      - C:\Users\KDUWADI\Desktop\NREL_Projects\TUNISIA\data\evolve_docker_data\postgres_data1:/var/lib/postgresql/data
